#!/usr/bin/env bash

echo "Creating database gostrap..."
createdb gostrap

echo "Running migration on postgres://Bruno@localhost:5432/gostrap?sslmode=disable..."
migrate -url postgres://Bruno@localhost:5432/gostrap?sslmode=disable -path ./migrations up

echo "Creating database gostrap-test"
createdb gostrap-test

echo "Running migration on postgres://Bruno@localhost:5432/gostrap-test?sslmode=disable..."
migrate -url postgres://Bruno@localhost:5432/gostrap-test?sslmode=disable -path ./migrations up